resources:
- name: picam-visualizer
  type: git
  source:
    branch: master
    uri: https://github.com/uendelig/picam-visualizer.git

jobs:
- name: Build
  plan:
  - get: picam-visualizer
    trigger: true
  - task: build-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
      inputs:
        - name: picam-visualizer
      outputs:
        - name: picam-visualizer/dist
      run:
        path: sh
        args:
        - -exc
        - |
          cd picam-visualizer
          npm install
          npm run build
          echo "Build Finished"
