resources:
- name: picam-visualizer-repo-resource
  type: git
  source:
    branch: master
    uri: https://github.com/uendelig/picam-visualizer.git

jobs:
- name: Run-automatically
  plan:
  - get: picam-visualizer-repo-resource
    trigger: true
  - task: build-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Build auto"
